deployment:
  tasks:
    - export DEPLOYPATH=/home/example/public_html/
    - /bin/cp index.css $DEPLOYPATH
    - /bin/cp index.js $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp contactus.html $DEPLOYPATH
    - /bin/cp contactus.js $DEPLOYPATH
    - /bin/cp contactus.css $DEPLOYPATH
    - /bin/cp product.html $DEPLOYPATH
    - /bin/cp product.css $DEPLOYPATH
    - /bin/cp product.js $DEPLOYPATH
