deployment:
  tasks:
    - export DEPLOYPATH=/home/example/public_html/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R javascript $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp contactus.html $DEPLOYPATH
    - /bin/cp product.html $DEPLOYPATH